version: "3"
services:
    api:
      #build: .
      image: dineshaponso/fastapi
      depends_on:
          - postgres
      ports: 
          - 80:8000
      # volumes: 
      #     - ./:/usr/scr/app:ro
      # command: bash -c "uvicorn app.main_sqlalchemy:app --host 0.0.0.0 --port 8000"
      # env_file:
      #     - ./.env
      environment:
        - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - SECRET_KEY=${SECRET_KEY}
        - ALGORITHM=${ALGORITHM}
        - ACCESS_TOKEN_EXPIRE_MIN=${ACCESS_TOKEN_EXPIRE_MIN}
  
    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DATABASE_NAME}

      volumes:
        - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db:
